/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <string>

/* Header for class com_fly_tkuilife_utils_SecretResource */

#ifndef _Included_com_fly_tkuilife_utils_SecretResource
#define _Included_com_fly_tkuilife_utils_SecretResource
#ifdef __cplusplus
extern "C" {
#endif

const char* SIGNATURE_MD5 = "";


/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getAPIKey_Weather
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getAPIKey_1Weather
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getAPIKey_Transportation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getAPIKey_1Transportation
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getAppKey_Teansportation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getAppKey_1Teansportation
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getAES256Key_TKU
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getAES256Key_1TKU
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getAES256Iv_TKU
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getAES256Iv_1TKU
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Curriculum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Curriculum
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/CoWork/XML/wsStuEleList2XML_WEEK.cshtml");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Exam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Exam
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/CoWork/XML/wsStuExamList2XML.cshtml");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_CourseChangeTemporary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1CourseChangeTemporary
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/CoWork/XML/wsStuLveReg.cshtml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_CourseChangePermanent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1CourseChangePermanent
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/CoWork/XML/wsStuCrsChg.cshtml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Grade
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Grade
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/CoWork/XML/wsStuSemScoQuery2XML.cshtml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Transportation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Transportation
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ptx.transportdata.tw/MOTC/v2/Bus/EstimatedTimeOfArrival/City/");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Weather
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Weather
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://opendata.cwb.gov.tw/api/v1/rest/datastore/");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_TodayAnnounce
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1TodayAnnounce
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/today-1.xml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_RecentAnnounce
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1RecentAnnounce
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/news-0.xml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Event
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Event
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/act-0.xml");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_Pc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1Pc
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http:tkuipcedu.tku.edu.tw:1689/TKU_iLife");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorBusStop27
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorBusStop27
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam2.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorBusStop28
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorBusStop28
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam1.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorPlayground
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorPlayground
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam3.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorBasketballCourt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorBasketballCourt
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam4.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorTennisCourt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorTennisCourt
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam9.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorFiveTiger
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorFiveTiger
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam7.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorElevator
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorElevator
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam5.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MonitorPostOffice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MonitorPostOffice
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://163.13.240.165/cam8.jpg");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MapBuilding
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MapBuilding
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/data_info_location.ashx?ty=json");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MapFood
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MapFood
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/data_info_location.ashx?ty=json&lyr=food");
}

/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_MapBus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1MapBus
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/data_info_location.ashx?ty=json&lyr=bus");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_CalendarFirstSemester
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1CalendarFirstSemester
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/XML/cal1.xml");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_CalendarSecondSemester
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1CalendarSecondSemester
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/XML/cal2.xml");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_NewsPaperLatest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1NewsPaperLatest
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/Times/new-cht");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_NewsPaperLatestImg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1NewsPaperLatestImg
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://tkutimes.tku.edu.tw/ashx/getILPic150.ashx?im=");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_EResourcesNews
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1EResourcesNews
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://www.lib.tku.edu.tw/xhr/announcements/rssfeed/59519819.rss");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_NewsPaperNews
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1NewsPaperNews
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/Times/new-");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_NewsPaperGallery
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1NewsPaperGallery
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ilife.tku.edu.tw/Data/xml/Times/pic_db");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_LibraryOpen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1LibraryOpen
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("http://info.lib.tku.edu.tw/tkuilife/open.xml");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_BusStationList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1BusStationList
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ptx.transportdata.tw/MOTC/v2/Bus/DisplayStopOfRoute/City/");
}
/*
 * Class:     com_fly_tkuilife_utils_SecretResource
 * Method:    getURL_BusLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fly_tkuilife_utils_SecretResource_getURL_1BusLocation
        (JNIEnv *env, jobject clz){
    return env->NewStringUTF("https://ptx.transportdata.tw/MOTC/v2/Bus/RealTimeNearStop/City/");
}

jobject getContext(JNIEnv *env){
    jobject context = NULL;
    jclass clz = env->FindClass("com/fly/tkuilife/utils/Global");
    if(clz!=NULL){
        jmethodID  id = env->GetStaticMethodID(clz, "getContext", "()Landroid/content/Context;");
        if(id!=NULL) context = env->CallStaticObjectMethod(clz, id);
        env->DeleteLocalRef(clz);
    }
    return context;
}

void ByteToHex(const char *source, char *dest, int sourceLen){
    int  i;
    char szTmp[3];
    for( i = 0; i < sourceLen; i++ ){
        sprintf( szTmp, "%02X", (unsigned char) source[i] );
        memcpy( &dest[i * 2], szTmp, 2 );
    }
    return;
}

jstring MD5Encrypt(JNIEnv *env, jbyteArray source){

    jclass clz_MessageDigest = env->FindClass("java/security/MessageDigest");
    jmethodID  id_getInstance = env->GetStaticMethodID(clz_MessageDigest, "getInstance", "(Ljava/lang/String;)Ljava/security/MessageDigest;");
    jobject messageDigest = env->CallStaticObjectMethod(clz_MessageDigest, id_getInstance, env->NewStringUTF("md5"));

    jmethodID id_update = env->GetMethodID(clz_MessageDigest, "update", "([B)V");
    env->CallVoidMethod(messageDigest, id_update, source);

    jmethodID id_digest = env->GetMethodID(clz_MessageDigest, "digest", "()[B");
    jbyteArray byte_array_sign = (jbyteArray) env->CallObjectMethod(messageDigest, id_digest);

    jsize arraylength_sign = env->GetArrayLength(byte_array_sign);
    jbyte* pointer_byte_array_elements = env->GetByteArrayElements(byte_array_sign, NULL);
    size_t length = (size_t) arraylength_sign*2+1;
    char* char_res = (char*) malloc(length);
    memset(char_res, 0, length);

    ByteToHex((const char*)pointer_byte_array_elements, char_res, arraylength_sign);
    *(char_res + arraylength_sign*2) = '\0';

    jstring res = env->NewStringUTF(char_res);
    env->ReleaseByteArrayElements(byte_array_sign, pointer_byte_array_elements, JNI_ABORT);
    free(char_res);

    return res;

}

jstring loadSignature(JNIEnv *env, jobject context){

    jclass cls = env->GetObjectClass(context);
    jmethodID mid = env->GetMethodID(cls, "getPackageManager", "()Landroid/content/pm/PackageManager;");

    jobject pm = env->CallObjectMethod(context, mid);

    mid = env->GetMethodID(cls, "getPackageName", "()Ljava/lang/String;");
    jstring packageName = (jstring) env->CallObjectMethod(context, mid);

    cls = env->GetObjectClass(pm);
    mid = env->GetMethodID(cls, "getPackageInfo", "(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;");
    jobject packageInfo = env->CallObjectMethod(pm, mid, packageName, 0x40); //GET_SIGNATURES = 64;
    cls = env->GetObjectClass(packageInfo);
    jfieldID fid = env->GetFieldID(cls, "signatures", "[Landroid/content/pm/Signature;");
    jobjectArray signatures = (jobjectArray) env->GetObjectField(packageInfo, fid);
    jobject signature = env->GetObjectArrayElement(signatures, 0);

    cls = env->GetObjectClass(signature);
    mid = env->GetMethodID(cls, "toByteArray", "()[B");
    jbyteArray signatureByteArray = (jbyteArray) env->CallObjectMethod(signature, mid);

    return MD5Encrypt(env, signatureByteArray);

}

jboolean checkSignatureMD5(JNIEnv *env, jobject context){

    jstring signature = loadSignature(env, context);
    jstring vailded_signature = env->NewStringUTF(SIGNATURE_MD5);

    const char *charSignature = env->GetStringUTFChars(signature, NULL);
    const char *charVaildedSignature = env->GetStringUTFChars(vailded_signature, NULL);

    if(charSignature!=NULL && charVaildedSignature!=NULL){
        if(strcmp(charSignature, charVaildedSignature)==0) return JNI_TRUE;
    }

    return JNI_FALSE;
}

jint JNI_OnLoad(JavaVM *vm, void *reserved){
    JNIEnv *env;
    if (vm->GetEnv((void **) (&env), JNI_VERSION_1_6) != JNI_OK) return -1;
    if (checkSignatureMD5(env, getContext(env))!=JNI_TRUE) return -1;
    return JNI_VERSION_1_6;
}



#ifdef __cplusplus
}
#endif
#endif
